# -*- coding: utf-8 -*-
"""project-exposys.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPcNOzowevg8cIhiVO14mszfRK_Ewpg_
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as py

url = "https://raw.githubusercontent.com/vidya-code/Project-exposys/main/50_Startups.csv?token=GHSAT0AAAAAACCH6767XZMVNM7DSZTDWEMIZCUT3DQ"

data=pd.read_csv(url)

data.head

data.info()

data.isna()

data.isna().sum()

data.isnull().sum()

# For  asingle column

data['Administration'].isna().sum()

data.isnull().sum().sum()

list(data.columns)

from scipy import stats
stats.pearsonr(data['R&D Spend'], data['Profit'])

cormat = data.corr()
round(cormat,2)

sns.heatmap(cormat)